config/routes.rb
Rails.application.routes.draw do
  get 'main', to: 'users#main'
  get '/userPost', to: 'users#userPost'
  get '/users/destroy', to: 'users#destroy'
  get '/users/Create_fast', to: 'users#revive'
  get 'userPost/:id', to: 'users#userPost'
  
  resources :users #do
    #resources :posts
  #end
  resources :posts
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
#class LoggingIn < ActiveModel::Validator
#	def validate_pass(record)
#		if record.password != User.find_by(email: record.email).password
#			record.errors.add :base, "password or email is not valid"
#		end
#	end
#end

class User < ApplicationRecord
	has_many :posts
	validates :email, uniqueness: true, presence: true
	has_secure_password
	#validates_with LoggingIn
	#validates :name, length: {minimum : 2}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/main_controller.rb
class MainController < ApplicationController
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]
  #before_action :set_user
  before_action :logged_in

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
    if @post.user_id != session[:user_id]
      redirect_to posts_path, notice: "That is not your post sir, yours user id is #{session[:user_id]}"
    end
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
    if @post.user_id != session[:user_id]
      redirect_to posts_path, notice: "That is not your post sir, yours user id is #{session[:user_id]}"
    end
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)
    if post_params[:user_id].to_i != session[:user_id]
      redirect_to userPost_path, notice: "That is not your user id sir, yours user id is #{session[:user_id]}"
    else
      respond_to do |format|
        if @post.save
          format.html { redirect_to userPost_path, notice: "Post was successfully created." }
          format.json { render :show, status: :created, location: @post }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @post.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    @test = post_params[:user_id]
    if post_params[:user_id].to_i != session[:user_id]
      redirect_to post_path(@post), notice: "That is not your user id sir, yours user id is #{session[:user_id]}"
    else  
      respond_to do |format|
        if @post.update(post_params)
          format.html { redirect_to post_path(@post), notice: "Post was successfully updated." }
          format.json { render :show, status: :ok, location: @post }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @post.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    if @post.user_id != session[:user_id]
      redirect_to posts_path, notice: "That is not your post sir, yours user id is #{session[:user_id]}"
    else
      @post.destroy
      respond_to do |format|
        format.html { redirect_to userPost_path, notice: "Post was successfully destroyed." }
        format.json { head :no_content }
      end
    end
  end

  #def userPost
  #end

  private
    # Use callbacks to share common setup or constraints between actions.
    def logged_in
      if(session[:user_id])
        @user = User.find_by(id: session[:user_id])
        return true
      else
        redirect_to main_path, notice: "you did not login"
      end
    end

    def set_post
      @post = Post.find(params[:id])
    end

#    def set_user
#      @user = User.find_by(id: session[:user_id])
#    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:msg, :user_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ] # to do set_user in show edut update and destroy
  before_action :logged_in, except: %i[ main new create ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        session[:user_id] = @user.id
        format.html { redirect_to @user, notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy
#    respond_to do |format|
#      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
#      format.json { head :no_content }
#    end
  end
  
  def revive
    @name = params[:name]
    @email = params[:email]
    User.create(name: @name, email: @email, birthday: DateTime.current.to_date, address: "unknown", postal_code: "unknown", pasword: "abc")
  end

  def main
    session[:user_id] = nil # cookie
    logging = params[:commit]
    loginSuccess = false
    @user = User.find_by(email: params[:email])
    if @user && @user.authenticate(params[:password]) #@user -> check is it null
      redirect_to userPost_path
      loginSuccess = true
      session[:user_id] = @user.id # cookie
    end
    if !loginSuccess && params[:commit] == "Login"
      redirect_to '/main', notice: "Either email or password is incorrect :)"
    end
  end

  def userPost
    @user = User.find_by(id: session[:user_id])
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def logged_in
      if(session[:user_id])
        return true
      else
        redirect_to main_path, notice: "you did not login"
      end
    end

    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:email, :name, :birthday, :address, :postal_code, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Class4</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :msg %>
    <%= form.text_field :msg %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id , :value => @user.id%>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<%# form_with(url: "/users/#{@user.id}/posts/#{@post.id}", model: post) do |form| %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

session id is <%= session[:user_id] %><br><br>

<%= render 'form', post: @post %>

<%= link_to 'Show', post_path(@post)%> |
<%= link_to 'Back', userPost_path%>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Current User</h1>
<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Birthday:</strong>
  <%= @user.birthday %>
</p>

<p>
  <strong>Address:</strong>
  <%= @user.address %>
</p>

<p>
  <strong>Postal code:</strong>
  <%= @user.postal_code %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

<h1>All posts</h1>

<table>
  <thead>
    <tr>
      <th>Msg</th>
      <th>user_id</th>
      <th>updated time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.msg %></td>
        <td><%= post.user_id %></td>
        <td><%= post.updated_at %></td>
        <td><%= link_to 'Show', post_path(post) %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post_path(post), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Log out', main_path %> |
<%= link_to 'back to your posts', userPost_path %> |
<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', userPost_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Msg:</strong>
  <%= @post.msg %>
</p>

<p>
  <strong>Update Time:</strong>
  <%= @post.updated_at %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', userPost_path %>

app/views/posts/userPost.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Birthday:</strong>
  <%= @user.birthday %>
</p>

<p>
  <strong>Address:</strong>
  <%= @user.address %>
</p>

<p>
  <strong>Postal code:</strong>
  <%= @user.postal_code %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

<table>
  <thead>
    <tr>
      <th>Msg</th>
      <th>Time Updated</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user.posts.each do |post| %>
      <tr>
        <td><%= post.msg %></td>
        <td><%= post.updated_at %></td>
        <td><%= link_to 'Show', user_post_path(@user, post) %></td>
        <td><%= link_to 'Edit', edit_user_post_path(@user, post) %></td>
        <td><%= link_to 'Destroy', user_post_path(@user, post), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_user_post_path(@user) %> |
<%= link_to 'Log out', '/main' %>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :birthday %>
    <%= form.date_select :birthday %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div class="field">
    <%= form.label :postal_code %>
    <%= form.text_field :postal_code %>
  </div>

  <div class="password">
    <%= form.label :password %>
    <%= form.text_field :password %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/destroy.html.erb
<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Birthday:</strong>
  <%= @user.birthday %>
</p>

<p>
  <strong>Address:</strong>
  <%= @user.address %>
</p>

<p>
  <strong>Postal code:</strong>
  <%= @user.postal_code %>
</p>

<%= link_to 'Back', users_path %>
<%= link_to 'Create_fast', users_path.concat("/Create_fast?name=#{@user.name}&email=#{@user.email}")%>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<%= users_url%>
<%= users_path%>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Name</th>
      <th>Birthday</th>
      <th>address</th>
      <th>postal code</th>
      <th>password</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.name %></td>
        <td><%= user.birthday %></td>
        <td><%= user.address %></td>
        <td><%= user.postal_code %></td>
        <td><%= user.password %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/main.html.erb
<%= form_with url: "/main", method: :get do |form| %>
  <p id="notice"><%= notice %></p>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.text_field :password %>
  </div>

  <div class="actions">
    <%= form.submit "Login"%>
  </div>
<% end %>

<%= link_to 'Sign up', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/revive.html.haml
%h1 Create Fast
Create name : #{@name}
%br/
Create email : #{@email}
%br/
Create birthday : #{DateTime.current.to_date}
%br/
Create address : unknown
%br/
Create postal_code : unknown
%br/
= link_to 'Back', users_path

app/views/users/reviveee.html.erb
<h1>Create Fast</h1>

Create name : <%= @name%>
Create email : <%= @email%>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Birthday:</strong>
  <%= @user.birthday %>
</p>

<p>
  <strong>Address:</strong>
  <%= @user.address %>
</p>

<p>
  <strong>Postal code:</strong>
  <%= @user.postal_code %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/users/userPost.html.erb
<p id="notice"><%= notice %></p>

your user id is: <%= @user.id%>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Birthday:</strong>
  <%= @user.birthday %>
</p>

<p>
  <strong>Address:</strong>
  <%= @user.address %>
</p>

<p>
  <strong>Postal code:</strong>
  <%= @user.postal_code %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

<table>
  <thead>
    <tr>
      <th>Msg</th>
      <th>Time Updated</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user.posts.each do |post| %>
      <tr>
        <td><%= post.msg %></td>
        <td><%= post.updated_at %></td>
        <td><%= link_to 'Show', post_path(post) %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post_path(post), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %> |
<%= link_to 'see all posts', posts_path %> |
<%= link_to 'Log out', '/main' %>